### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by oialvarez** [oialvarez/viajante#10]
Se crear una landing page, donde el viajante pueda seleccionar alguna zona de Chile para revisar.

Las zonas serían Norte, Centro, Sur y Austral. Cada zona es cliqueable y debe llevar a un detalle de zona. Cada zona sería una imagen.

**Comment by oialvarez** [comment]
Un campo de texto auto-completable para escribir la ciudad donde se requiere buscar.

**Comment by SirErisstolf** [comment]
Debemos reescribir esta historia
