### ISSUE TITLE
Website hospedaje

### ISSUE THREAD

**Issue by oialvarez** [oialvarez/viajante#13]
El website del hospedaje será administrado por el representante del mismo.

Habrá varios templates disponibles para elegir. 

El representante podrá definir, imágenes, videos, servicios, precios de habitaciones o cabañas, datos de contacto, zona dentro del site (eg: cabanashorcon.viajante.cl)

**Comment by oialvarez** [comment]
ideal sería que el sitio actual del hospedaje se pudiese mostrar dentro de la plataforma, ejemplo: http://www.cabanashorcon.cl/

**Comment by SirErisstolf** [comment]
iframe

**Comment by SirErisstolf** [comment]
Voy a cerrar esta tarea, deberiamos crear tareas mas pequeñas
