### ISSUE TITLE
"Hola Mundo" 

### ISSUE THREAD

**Issue by SirErisstolf** [oialvarez/viajante#3]
Crear una pagina sencilla que extraiga datos desde una coleccion (json) de mongo y mostrarla usando angular

**Comment by oialvarez** [comment]
¿al parecer aun te falta para cerrar esta tarea?

**Comment by SirErisstolf** [comment]
Si, la iba a hacer ayer, pero no tuve tiempo.

**Comment by oialvarez** [comment]
falta menos

**Comment by SirErisstolf** [comment]
Yo creo que esto se puede cerrar, en el commit d958a9813b23aa4de922b8130dff7fda884d371e pude mostrar info desde mongo con una pagina nueva
